services:
  redis:
    container_name: redis
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: campfire
      POSTGRES_USER: campfire
    ports:
      - "5432:5432"
