services:
  rabbit_mq:
    container_name: rabbit_mq
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: campfire
      RABBITMQ_DEFAULT_PASS: campfire
    ports:
      - "5672:5672"
      - "15672:15672"
  redis:
    container_name: redis
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
