version: "3.7"
name: cafe

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: campfire
      POSTGRES_USER: campfire
    ports:
      - "5432:5432"
