name: campfire-wallets
author: Bruce
main: io.shaded.campfire.wallets.CampfireWalletsPlugin
version: 0.0.1
api-version: '1.20'
commands:
  balance:
    description: Balance
    aliases:
      - bal
  pay:
    description: Pay another person
  add-funds:
    description: add funds to a wallet
  remove-funds:
    description: remove funds from a wallet
