name: campfire-homes
author: Bruce
main: io.shaded.campfire.homes.CampfireHomesPlugin
version: 0.0.1
api-version: '1.20'
commands:
  home:
    description: Teleport home
    aliases:
      - homes
  sethome:
      description: Set a home location in a world
  delhome:
      description: Deletes a home in a world

